<a href="https://colab.research.google.com/github/SathishDissanayaka/Information-Retrieval-Web-Analytics-Labs/blob/main/IRWA_Lab05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Question 01(TF-IDF)
#Count Vectorizer (TF matrix)
from sklearn.feature_extraction.text import CountVectorizer
#CountVectorizer is used to convert a collection of text documents into a matrix of token (word) counts.
document1 = 'the man went out for a walk for'
document2 = 'the children sat around the fire'
vectorizer = CountVectorizer()
#This object will: Tokenize the text (split into words),Convert all text to lowercase,Remove punctuation,Build a vocabulary of unique words across all documents
tf_matrix = vectorizer.fit_transform([document1, document2])
#fit->identifies all unique words in document1 and document2 & transform → Converts each document into a vector of word counts
"""tf_matrix is a sparse matrix where:
Rows = documents (document1 = row 0, document2 = row 1)
Columns = unique words in vocabulary
Values = frequency of each word in that document"""
tf_array = tf_matrix.toarray()
#Converts the sparse matrix to a regular NumPy array for easier viewing.
print(tf_array)

[[0 0 0 2 1 1 0 1 1 1]
 [1 1 1 0 0 0 1 2 0 0]]


In [2]:
import numpy as np

In [7]:
#TF-IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
document1 = 'the man went out for a walk'
document2 = 'the children sat around the fire'
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([document1, document2])
tfidf_array = tfidf_matrix.toarray()
print(np.round(tfidf_array,2))
#Prints the TF-IDF matrix with values rounded to 2 decimal places.

[[0.   0.   0.   0.43 0.43 0.43 0.   0.3  0.43 0.43]
 [0.41 0.41 0.41 0.   0.   0.   0.41 0.58 0.   0.  ]]


In [9]:
#Q2(find Cosine Similarity)
#Cosine similarity is a measure of how similar two vectors are, based on the angle between them.
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
document1 = 'the man went out for a walk'
document2 = 'the children sat around the fire'
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([document1, document2])
cosine_sim = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])
#This value tells you how similar the two documents are (0 = very different, 1 = identical).
print(cosine_sim)

[[0.17578608]]
